version: '3'

services:

  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    image: ${HUB_IMAGE_NAME}:latest
    ports:
      - "3001:8000"
    container_name: ${HUB_CONTAINER_NAME}
    restart: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "jupyterhub_data:${HUB_HOST_VOLUME_FOLDER}:rw"
      - ${HUB_HOST_CONFIG_FOLDER}:${HUB_CONFIG_FOLDER}
      - "/etc/shadow:/etc/shadow"
      - "/etc/passwd:/etc/passwd"
      - "/etc/pam.d:/etc/pam.d"
    environment:
      LAB_IMAGE_NAME: ${LAB_IMAGE_NAME}
      HUB_IP: ${HUB_CONTAINER_NAME}
      HUB_NETWORK_NAME: ${HUB_NETWORK_NAME}
    env_file:
      - ./secrets/.env.oauth2
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HUB_FRONTEND_HOST}"
      - "traefik.docker.network=${HUB_NETWORK_NAME}"
    command: >
        jupyterhub -f ${HUB_CONFIG_FOLDER}/jupyterhub_config.py


volumes:
    jupyterhub_data:
        external:
          name: "${HUB_HOST_VOLUME_NAME}"

networks:
    default:
      external:
        name: ${HUB_NETWORK_NAME}
    env_file:
        - .env

