version: '3'

services:

  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    image: ${JUPYTERHUB_IMAGE_NAME}
    ports:
      - "3001:8000"
    container_name: ${HUB_CONTAINER_NAME}
    restart: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "jupyterhub_data:${DATA_VOLUME_CONTAINER}"
      - ${HOST_CONFIG_FOLDER}:/etc/jupyterhub
      - "/etc/shadow:/etc/shadow"
      - "/etc/passwd:/etc/passwd"
      - "/etc/pam.d:/etc/pam.d"
    environment:
      DOCKER_JUPYTER_CONTAINER: ${LOCAL_NOTEBOOK_IMAGE}
      HUB_IP: ${HUB_CONTAINER_NAME}
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
    env_file:
      - ./secrets/.env.oauth2
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${FRONTEND_HOST}"
      - "traefik.docker.network=${DOCKER_NETWORK_NAME}"
    command: >
        jupyterhub -f /srv/jupyterhub/jupyterhub_config.py


volumes:
    jupyterhub_data:
        external:
          name: "${DATA_VOLUME_HOST}"

networks:
    default:
      external:
        name: ${DOCKER_NETWORK_NAME}
